# Generated by Django 3.1.7 on 2021-04-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_dz', '0003_auto_20210422_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('telefono', models.IntegerField(max_length=12, verbose_name='Numero de telefono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('Mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
